"""
Dholera SIR — Spatial Intelligence Dashboard
pages/__init__.py  →  Shared layout template + Master GEE authentication
"""

import os
import json
import solara
import ee


# ──────────────────────────────────────────────────────────────────────
#  Master GEE Authentication (Executes once at server boot)
# ──────────────────────────────────────────────────────────────────────

def _init_gee():
    """
    Initializes Google Earth Engine securely.
    Reads a single Service Account JSON text string stored in cloud secrets.
    """
    try:
        sa_key_json = os.environ.get("EE_SERVICE_ACCOUNT_KEY", "")

        if sa_key_json:
            key_dict = json.loads(sa_key_json)
            
            # Instantiates explicit credentials directly from the key dictionary data
            credentials = ee.ServiceAccountCredentials(
                client_email=key_dict["client_email"], 
                key_data=json.dumps(key_dict)
            )
            ee.Initialize(credentials=credentials)
            print("✅ GEE Initialized successfully via Service Account Private Key.")
            
        else:
            # Local machine fallback: reads path tokens generated by 'earthengine authenticate'
            ee.Initialize()
            print("✅ GEE Initialized successfully via local terminal credentials.")
            
    except Exception as e:
        print(f"⚠️ GEE System Initialization Failure: {e}")


# Run the initialization immediately when the Solara app starts up
_init_gee()


# ──────────────────────────────────────────────────────────────────────
#  Shared Layout Template Wrapper (Standard Native Theme)
# ──────────────────────────────────────────────────────────────────────

@solara.component
def Layout(children=[]):
    """
    Universal app shell template. Solara automatically scans the
    remaining files in your pages/ directory to populate the sidebar navigation.
    """
    # Use Solara's native AppLayout to build a standard scientific dashboard container
    with solara.AppLayout(navigation=True):
        
        # ── Global App Header Bar ──
        with solara.AppBar():
            with solara.Row(style={"align-items": "center", "gap": "12px"}):
                solara.Text("🛰️", style={"font-size": "24px"})
                with solara.Column(style={"gap": "2px"}):
                    solara.Markdown("### Dholera SIR — Spatial Intelligence Dashboard")
                    solara.Text(
                        "Google Earth Engine · Sentinel-2 · VIIRS · SAR Imagery", 
                        style={"font-size": "11px", "opacity": "0.7"}
                    )

        # ── Reactive Page Canvas Container ──
        # Provides clean, uniform padding for whatever child page script is loaded
        with solara.Padding(24):
            solara.Column(children=children, style={"width": "100%"})