"""
Dholera SIR — Spatial Intelligence Dashboard
pages/__init__.py  →  Shared layout template + Master GEE authentication
"""

import os
import json
import solara
import ee


# ──────────────────────────────────────────────────────────────────────
#  Master GEE Authentication (Executes once at server boot)
# ──────────────────────────────────────────────────────────────────────

def _init_gee():
    """
    Initializes Google Earth Engine securely.
    Reads a single Service Account JSON text string stored in cloud secrets.
    """
    try:
        # Standardized single-key configuration profile
        sa_key_json = os.environ.get("EE_SERVICE_ACCOUNT_KEY", "")

        if sa_key_json:
            key_dict = json.loads(sa_key_json)
            
            # Instantiates explicit credentials directly from the key dictionary data
            credentials = ee.ServiceAccountCredentials(
                client_email=key_dict["client_email"], 
                key_data=json.dumps(key_dict)
            )
            ee.Initialize(credentials=credentials)
            print("✅ GEE Initialized successfully via Service Account Private Key.")
            
        else:
            # Local machine fallback: reads path tokens generated by 'earthengine authenticate'
            ee.Initialize()
            print("✅ GEE Initialized successfully via local terminal credentials.")
            
    except Exception as e:
        print(f"⚠️ GEE System Initialization Failure: {e}")


# Run the initialization immediately when the Solara app starts up
_init_gee()


# ──────────────────────────────────────────────────────────────────────
#  Shared Layout Template Wrapper
# ──────────────────────────────────────────────────────────────────────

@solara.component
def Layout(children=[]):
    """
    Universal app shell template. Solara automatically scans the
    remaining files in your pages/ directory to populate the sidebar tabs.
    """
    with solara.Column(
        style="min-height: 100vh; background: #0d1117; width: 100%; display: flex; flex-direction: column;"
    ):

        # ── Top Identity Banner ──────────────────────────────────────────
        with solara.Row(
            style=(
                "background: linear-gradient(90deg, #0d1117 0%, #161b22 100%);"
                "border-bottom: 1px solid #30363d;"
                "padding: 16px 32px;"
                "align-items: center;"
                "gap: 16px;"
            )
        ):
            solara.Text(
                "🛰️",
                style="font-size: 28px; line-height: 1;",
            )
            with solara.Column(style="gap: 4px;"):
                solara.Text(
                    "Dholera SIR — Spatial Intelligence Dashboard",
                    style=(
                        "font-family: 'IBM Plex Mono', monospace;"
                        "font-size: 18px;"
                        "font-weight: 700;"
                        "color: #e6edf3;"
                        "letter-spacing: 0.5px;"
                    ),
                )
                solara.Text(
                    "Google Earth Engine  ·  Sentinel-2  ·  VIIRS  ·  SAR Imagery",
                    style=(
                        "font-family: 'IBM Plex Mono', monospace;"
                        "font-size: 11px;"
                        "color: #8b949e;"
                        "letter-spacing: 1px;"
                    ),
                )

        # ── Reactive Page Canvas Container ─────────────────────────────────
        # Safe array containment mapping replaces erratic display unpacking
        with solara.Column(style="flex: 1; padding: 24px 32px; width: 100%;"):
            solara.Column(children=children, style="width: 100%;")